title: 'Fondacija Dušan Pavlović'
default_lang: sr
author:
  name: FDP
  email: office@fondacijadp.rs
taxonomies:
  - category
  - tag
metadata:
  description: 'Fondacija Dušan Pavlović nastala je iz želje za prenošenjem znanja i podsticanjem mladih talenata u oblasti ekologije, energetske efikasnosti, obnovljivih izvora energije i održivog razvoja.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
